export enum AuthErrorCodes {
    INVALID_TOKEN = 'INVALID_TOKEN',
    EXPIRED_TOKEN = 'EXPIRED_TOKEN',
    MISSING_TOKEN = 'MISSING_TOKEN',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
}

export enum PermissionErrorCodes {
    UNAUTHORIZED_ACCESS = 'UNAUTHORIZED_ACCESS',
    RESOURCE_OWNERSHIP_MISMATCH = 'RESOURCE_OWNERSHIP_MISMATCH',
    INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
}

export enum BusinessLogicErrorCodes {
    INVALID_OPERATION = 'INVALID_OPERATION',
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
    ITEM_ALREADY_EXISTS = 'ITEM_ALREADY_EXISTS',
    QUOTA_EXCEEDED = 'QUOTA_EXCEEDED',
    RATE_LIMITED = 'RATE_LIMITED',
}

export enum DatabaseErrorCodes {
    CONNECTION_FAILURE = 'CONNECTION_FAILURE',
    TIMEOUT = 'TIMEOUT',
    DUPLICATE_KEY = 'DUPLICATE_KEY',
}

export enum RequestErrorCodes {
    INVALID_INPUT = 'INVALID_INPUT',
    MISSING_PARAMETERS = 'MISSING_PARAMETERS',
    UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
    NOT_ACCEPTABLE = 'NOT_ACCEPTABLE',
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
}

export enum SystemErrorCodes {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
}

export enum ValidationErrorCodes {
    LENGTH_VALIDATION_FAILED = 'LENGTH_VALIDATION_FAILED',
    PATTERN_VALIDATION_FAILED = 'PATTERN_VALIDATION_FAILED',
    TYPE_VALIDATION_FAILED = 'TYPE_VALIDATION_FAILED',
}

export enum UserErrorCodes {
    USER_NOT_FOUND = 'USER_NOT_FOUND',
  }
  
export enum GeneralErrorCodes {
    RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
    INVALID_OPERATION = 'INVALID_OPERATION',
    ITEM_ALREADY_EXISTS = 'ITEM_ALREADY_EXISTS',
    ITEM_NOT_FOUND = 'ITEM_NOT_FOUND',
    DUPLICATE_KEY = 'DUPLICATE_KEY',
    CONNECTION_FAILURE = 'CONNECTION_FAILURE',
    TIMEOUT = 'TIMEOUT',
    INVALID_INPUT = 'INVALID_INPUT',
    MISSING_PARAMETERS = 'MISSING_PARAMETERS',
    UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',
}